paginate: 10
pygments: true
markdown: kramdown
tag_page_dir: tag
tag_feed_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed
permalink: /:year/:month/:day/:title/
url: http://realjenius.com
exclude: [README.md]